name: Check code format
run-name: ${{ github.actor }} checked format
on: push

jobs:
  check-format:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt -- --check
