name: Run all tests
run-name: ${{ github.actor }} run all tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose
