name: Run linter
run-name: ${{ github.actor }} ran the linter
on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy -- -D warnings