name: Check code format
run-name: ${{ github.actor }} checking format
on: push

jobs:
  measure-coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Test format
      run: cargo fmt -- --check
