name: Measure code coverage
run-name: ${{ github.actor }} measured code coverage
on: push

jobs:
  measure-coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install tarpaulin
      run: cargo install cargo-tarpaulin
    - name: Measure coverage
      run: cargo tarpaulin --ignore-tests --verbose
