name: Measure code coverage
run-name: ${{ github.actor }} measured code coverage
on: push

jobs:
  measure-coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/tarpaulin@v0.1.0
