name: Measure code coverage
run-name: ${{ github.actor }} measured code coverage
on: push

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Lint
      run: cargo clippy -- -D warnings