name: Run all defined tests
run-name: ${{ github.actor }} run all tests
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
