name: Check vulnerabilities
run-name: ${{ github.actor }} checked for vulnerabilities
on: push

jobs:
  measure-coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Intall audit
      run: cargo install cargo-audit
    - name: Run audit
      run: cargo audit
